# You can use this file to setup the service locally, and start all the
# containers at once.
#
# Usage:
# - setup all the environment variables referenced below
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - run `docker-compose up`

version: "3"

services:
  streamanalytics:
    image: azureiotpcs/iot-stream-analytics-java
    ports:
      - "9023:9023"
    environment:
      - PCS_STREAMANALYTICS_WEBSERVICE_PORT=9023
      - PCS_STREAMANALYTICS_DOCUMENTDB_CONNSTRING
      - PCS_IOTHUBREACT_HUB_NAME
      - PCS_IOTHUBREACT_HUB_ENDPOINT
      - PCS_IOTHUBREACT_HUB_PARTITIONS
      - PCS_IOTHUBREACT_ACCESS_CONNSTRING
